# Generated by Django 3.2.4 on 2021-12-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bloodbanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbanks',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
