# Generated by Django 3.2.4 on 2021-12-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bloodbanks_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodBanks',
        ),
    ]
